from .episodic_memory import EpisodicMemory
from .episodic_memory import RandomPolicy_EC
from .episodic_memory import distance_report_EpisodicMemory as distEM
from .episodic_memory import random_forget_EC
from .episodic_memory import EC_track_forgotten_states as track_forgoten_EM
from .episodic_memory import forget_least_recently_accessed_memory as lram_EM